export const StandardSizes = {
  L: {
    level: 2,
    fontSize: "2.5rem",
    mobileFontSize: "2rem",
    lineHeight: "44px",
    mobileLineHeight: "36px",
    letterSpacing: "-1px",
  },
  M: {
    level: 3,
    fontSize: "2rem",
    mobileFontSize: "1.5rem",
    lineHeight: "36px",
    mobileLineHeight: "28px",
    letterSpacing: "-0.8px",
  },
  S: {
    level: 4,
    fontSize: "1.5rem",
    mobileFontSize: "1.25rem",
    lineHeight: "28px",
    mobileLineHeight: "24px",
    letterSpacing: "-0.6px",
  },
  XS: {
    level: 5,
    fontSize: "1.25rem",
    mobileFontSize: "1.125rem",
    lineHeight: "24px",
    mobileLineHeight: "22px",
    letterSpacing: 0,
  },
  SH: {
    level: 6,
    fontSize: "1rem",
    mobileFontSize: "1rem",
    lineHeight: "20px",
    mobileLineHeight: "20px",
    letterSpacing: 0,
  },
};
